name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
